### ISSUE TITLE
Page 56: Arrow labelling mixup

### ISSUE THREAD

**Issue by adonaldson** [gilesbowkett/feedback-re-modern-front-end-dev-with-rails-and-puppies#29]
Thin arrow label points at fat arrow functions, fat arrow label points at thin arrow functions
e.g.
![screen shot 2016-11-29 at 17 14 10](https://cloud.githubusercontent.com/assets/19100/20720506/4b1332ba-b657-11e6-8be9-5cf3b460c5b4.png)

**Comment by gilesbowkett** [comment]
thanks! fixed this in a new version. (not released yet, but soon, I think.)
